export const SET_PROPERTY_DATA = 'SET_PROPERTY_DATA';
export const SET_APPOINTMENT_DATA = 'SET_APPOINTMENT_DATA';
export const SET_RENTAL_OFFER = 'SET_RENTAL_OFFER';
export const SET_TENANCY_ID = 'SET_TENANCY_ID';
export const SET_PROPERTY_COMPLIANCE_DATA = 'SET_PROPERTY_COMPLIANCE_DATA';
