export const LOGGED_IN_USER = 'LOGGED_IN_USER';
export const LOGGED_OUT_USER = 'LOGGED_OUT_USER';
export const LOGGED_IN_ERROR = 'LOGGED_IN_ERROR';
export const SET_USER_TYPE = 'SET_USER_TYPE';

export const SET_LANDLORDID = 'SET_LANDLORDID';
export const SET_TENANTID = 'SET_TENANTID';

export const SET_PERSONAL_DETAILS_ADDRESS = 'SET_PERSONAL_DETAILS_ADDRESS';
export const SET_PERSONAL_DETAILS_INFORMATION =
  'SET_PERSONAL_DETAILS_INFORMATION';
export const SET_PERSONAL_DETAILS_ERROR = 'SET_PERSONAL_DETAILS_ERROR';
